### ISSUE TITLE
Intermittent failure in python

### ISSUE THREAD

**Issue by Raul824** [moehmeni/syncedlyrics#52]
Sometimes while running in python I get below error message. They are intermittent, if I close vscodium and reopen and run the same it disappears.

```
Traceback (most recent call last):
    search(f"{srch_str}", allow_plain_format=False, save_path=f"{savepath}")
  File "site-packages/syncedlyrics/__init__.py", line 59, in search
    _l = provider.get_lrc(search_term)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/syncedlyrics/providers/musixmatch.py", line 120, in get_lrc
    tracks = body["track_list"]
             ~~~~^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:
Exception: list indices must be integers or slices, not str
```

srch_str="Liz Phair - Free Ride"
savepath="Liz Phair - Free Ride.lrc"

**Comment by moehmeni** [comment]
Thanks for the contribution, also sorry for late response. It's solved in v1.0.1.
